[versions]
binary-compatibility-validator = "0.13.0"
dokka = "1.8.10"
html-reporter = "0.6.3"
jacoco = "0.8.8"
kotest = "5.6.1"
kotlin-coroutines = "1.6.4"
kotlin-datetime = "0.4.0"
kotlin-serialisation = "1.5.0"
ktlint = "0.47.1"
publish = "1.1.0"
reckon = "0.16.1"
spotless = "6.18.0"
version-catalog-update = "0.8.0"
versions = "0.46.0"

[libraries]
html-reporter = { module = "com.michaelstrasser:kotest-html-reporter", version.ref = "html-reporter" }
kotest-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
kotest-junit = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-xml = { module = "io.kotest:kotest-extensions-junitxml-jvm", version.ref = "kotest" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin-datetime" }
kotlin-serialisation-hocon = { module = "org.jetbrains.kotlinx:kotlinx-serialization-hocon", version.ref = "kotlin-serialisation" }
kotlin-serialisation-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialisation" }
publish = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "publish" }
reckon = { module = "org.ajoberstar.reckon:reckon-gradle", version.ref = "reckon" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

[plugins]
binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-compatibility-validator" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
versionCatalogUpdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
